google-ID: ''

menu:
- {name: '.BASE', folder: 'pages', file: 'base.html'}
- {name: '.FAQ', folder: 'pages', file: 'faq.html'}
- {name: 'About Us', folder: 'pages', file: 'about.html'}

social:
- {icon: 'envelope', link: 'mailto:basetldomain@gmail.com'}
